PRAGMA encoding="UTF-8";
INSERT INTO ASSOCIATION (name)
VALUES ('BDS');

INSERT INTO ASSOCIATION (name)
VALUES ('BDD');

INSERT INTO ASSOCIATION (name)
VALUES ('BDE');

INSERT INTO ASSOCIATION (name)
VALUES ('BDA');