PRAGMA encoding="UTF-8";
INSERT INTO DEPARTMENT (name)
VALUES ('INFO');

INSERT INTO DEPARTMENT (name)
VALUES ('ETN');

INSERT INTO DEPARTMENT (name)
VALUES ('MAT');

INSERT INTO DEPARTMENT (name)
VALUES ('TE');